version: "3.9"

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend-application
    env_file:
      - .env
    restart: always
    ports:
      - "8000:800"
    volumes:
      - .:/srv/www
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl/
    networks:
      - backend
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data_prod:

networks:
  backend: