version: "3.9"

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/www