name: Docker deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'PR branch to deploy'
        required: true
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout selected PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: "."
          target: "~/assistant"

      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            cd ~/assistant
            docker compose down
            docker compose up -d --build